### ISSUE TITLE
Error Checking?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/public-profile-page-url-finder#3]
<img width="735" alt="profile-scrape-error" src="https://cloud.githubusercontent.com/assets/194400/10216508/894d8fce-6821-11e5-912c-b8a5b9e5c387.png">

Stack trace:
```sh
/Users/n/code/private/node_modules/public-profile-page-link-finder/lib/finder.js:22
    if( base.match(/linkedin.com/) ) {

TypeError: Cannot read property 'match' of undefined
    at profile (/Users/n/code/private/node_modules/public-profile-page-link-finder/lib/finder.js:22:13)
    at /Users/n/code/private/node_modules/public-profile-page-link-finder/lib/index.js:6:5
    at /Users/n/code/private/node_modules/public-profile-page-link-finder/lib/searcher.js:43:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by nelsonic** [comment]
This is caused by the fact that Simon changed his LinkedIn url...
https://www.google.co.uk/?q=Simon+Labondance+Founders+and+coders no longer has any result!
<img width="1106" alt="no-results-for-simon" src="https://cloud.githubusercontent.com/assets/194400/10216967/beb2c140-6824-11e5-981e-1b17e41272ba.png">

Confirmed by Simon:

<img width="654" alt="simon-not-in-google-results" src="https://cloud.githubusercontent.com/assets/194400/10216939/8fc49c6e-6824-11e5-8aea-c5c1123dbde1.png">

**Comment by SimonLab** [comment]
I'm back!
